### ISSUE TITLE
TODO on core GC

### ISSUE THREAD

**Issue by andychu** [oilshell/oil#1330]
- [x] Marked set is too big, has globals
  - #1346 
- [x] Desirable: non-recursive marking
- [x] EXPAND mycpp/examples to hit things we anticipate
- [x] GC stats on all the time, for unit tests
- [x] #1356 
- [x] Test proper graph traversal: https://oilshell.zulipchat.com/#narrow/stream/121539-oil-dev/topic/Parser.20slowness.20.28Oil.200.2E12.2E6.20Released.29/near/300383633
  - cycles are handled correctly
  - every node visited exactly once, even with duplicate roots -- 2022-10-01: TEST THIS
- [x] new GC header, supports 30 fields rather than 16 --  #1354 
- [x] Experiment with "Inverted" rooting? (Andy) -- to fix TEMP EXPRESSION problem
  -  https://oilshell.zulipchat.com/#narrow/stream/121539-oil-dev/topic/Third.20Rooting.20Strategy
  - this affects the StackRoots API, so it's part of the core GC
- [x] Remove `unordered_set` from `Collect()` and `MarkAllReferences()`
  - #1349 
- [x] Fix performance with `unordered_set` (in Allocate())  -- this is so slow it's obscuring other problems !
  -  quick: `reserve()` or  `std::hash<void*>`
  - but probably: a new data structure  implementation
- [x] Remove `unordered_set` from sweeping -- all_allocs should be a linked list, not an unordered_set
- [x] MAYBE: Do roots also need to be a linked list?   Or some kind of array/linked list hybrid?
  - Probably should use the same growable data structure on both roots and all allocs
  - would be nice: microbenchmarks for it vs. unordered_set -- #1309 
- [x] Garbage collection policy -- updating total heap bytes, etc.
  - did basic policy based on number of live objects
- [x] Optimization: **Lazy sweeping** 
  -  some links on Zulip: https://oilshell.zulipchat.com/#narrow/stream/121539-oil-dev/topic/Simple.20Mark.20and.20Sweep.20Design.20for.20a.20Shell

**Comment by andychu** [comment]
for core data structure, it might be OK to get something "reasonable", and then "crowd source" the optimized ones, since people like working on that sort of stuff

Right now unordered_set doesn't feel reasonable though

**Comment by andychu** [comment]
Outside core GC:

- #1176 
- #1322

**Comment by andychu** [comment]
### Performance Sanity Checks

- GC stats for number of collections -- expose this permanently as a flag or env?
  - and number of allocations.  
  - OILS_GC_STATS=1 ?
- Don't collect at the end of `osh_eval`
  - But do it in unit tests and mycpp/examples

**Comment by andychu** [comment]
We have lazy free() now!

https://github.com/oilshell/oil/commit/2a6eb37e487d3c58aee9ae2db9e0fe52b14e0ec0
