### ISSUE TITLE
Release automation: run spec tests with just OSH on different platforms

### ISSUE THREAD

**Issue by andychu** [oilshell/oil#167]
For OS X, BSDs, etc. where we might not want to bother building with `spec-bin.sh`

And maybe ARM Linux would be a good one too.  Although it would be nice to build binaries there.

**Comment by andychu** [comment]
This is is more significant now that we have a `__GLIBC__` test in `native/libc.c` for `extglob`.

In other words, some things don't work on Alpine now, and it would be nice to see that in the tests.

**Comment by andychu** [comment]
TODO: What are dependencies of spec tests?

- Python 2
- bash
- coreutils (including nproc #415)


Anything else?

I guess since they are confined to `test/spec.sh` and `test/spec-runner.sh`, we could make these more like POSIX scripts.  I guess it depends what we do with Python 2, which is needed to run `test/sh_spec.py`.

If we can use the same portability solution for all 3 deps, that would be nice.

Note `test/spec-bin.sh` builds binaries of other shells.  We don't technically need it for this task.  However we could use the same solution to build Python 2, bash, coreutils (which is admittedly onerous, but I guess BSDs are source-based anyway)

**Comment by andychu** [comment]
@jyn514 I realized the spec tests have a fairly significant gawk dependency.  The `match()` function is a useful extension -- see `test/spec-runner.sh`

So ideally we could package up these 4 dependencies somehow.   I don't think they are particularly weird or exotic.

I think putting `gawk` in $PATH is not too hard, as well as accounting for name differences with a tiny shell wrapper.

**Comment by andychu** [comment]
I think having something like:

```
$REPO/
  sh-env/
    darwin/
      nproc
      gawk
      rm
    freebsd/
      nproc
      gawk
      rm
```

Would work.  Some of these can be symlinks.

It's similar to the philosophy of avoiding #ifdefs.  The Go/Plan 9 guys advocate that -- they avoid #ifdefs and instead create portable interfaces.

**Comment by andychu** [comment]
This is kind of the opposite of #42 -- because we want to run at least some tests in a DIFFERENT environment!

**Comment by andychu** [comment]
Updated dependencies:

- Python 2 for `sh_spec.py` 
  - this was in Python 3 at some point, but I dropped support for it, woudln't be too hard to port again.  I think we mostly need `b''` everywhere.
- bash or known working version of Oil (might have arrays, associative arrays, etc. so not just POSIX)
- POSIX `rm`, etc.

OPTIONAL:

- GNU findutils for `xargs -P` parallelization

**Comment by jyn514** [comment]
I think you'll also need python-dev since you include Python.h during build/dev.sh all. Not sure if spec tests run with the dev build or the tarball.

**Comment by andychu** [comment]
This is for testing the end-user binaries, so the user just needs to run `./configure && make` etc.

No Python is needed to use Oil, either now or in the near future with `oil-native`!  Developing Oil is a different story, but this issue is basically moving spec tests from "dev" --> "distro maintainer" / "end user"

**Comment by andychu** [comment]
### TODO


- [ ] fold in `test/alpine2.sh` into `test/alpine.sh`
- [ ] Make it so you can copy an arbitrary tarball in, not just the `_release/oil-*.tar.gz` one
- [ ] "diff" functionality vs Ubuntu spec results
  - [ ] look into failures.  Some tests need to be modified.  Categorize them?
- [ ] Make sure other people can successfully run it.  Document it

Later:

- [ ] Run on OS X.  This seems pretty feasible now
  - [ ] `gawk` is a remaining problem

**Comment by andychu** [comment]
#70 is really a specific instance of this issue

**Comment by andychu** [comment]
Pinging this since it came up in the #oil-dev meeting

i.e. verifying a tarball/binary built with Nix
