### ISSUE TITLE
Oils 0.21.0 TODO

### ISSUE THREAD

**Issue by andychu** [oilshell/oil#1828]
A bunch of polish over Oils 0.20.0

- OSH 
  -  [x] Brace expansion compatibility (Simon Michael)
  - [x] ESRCH bug with pipelines and interactive shell -- multiple  people ran into this
-  Docs
   - [ ] publish ref check metrics
   - [x] `doc/error-catalog.md` - var/setvar, `\\` rules, OILS-ERR-10
- Translation
   - [x] Fix flag spec bug
   - [x] Fix all bugs?  delta cpp OSH = 4 and delta cpp YSH = 11, so it's within reach
- YSH
  -  [x] `const x` bug  - #1784 
  - [ ] @() semantics -- #1126 
  - [x] #1785 
  - [x] #1826 
  - [x] #1762 
  - [ ] #1850 
  - [ ] #1849 
  - [ ] #1841 
  - [x] rename toJ8() fromJ8() -> toJson8() fromJson8()
  - [ ] more breaking changes like `shopt --unset copy_env`
  - [ ] argv and proc simplifications mentioned on blog
- J8
  - [x] J8 refactor to remove self.spaces
  - [ ] json/json8 builtin should take named args, not flags
- ASDL
  - [x] omit  shared ref in C++ (already done in Python)

----

LATER, deferred

- Other YSH
  - [ ] Eggex names exported by `~`
  - [ ] `Str => replace()` could take a function (low priority)
  - [ ] is there anything with REG_NOTBOL?
- J8
  - [ ] line-based error messages for J8 - also affects NIL8
  - [ ] check max code point in survey, json string, j8 string, code string
- ASDL
  - [ ] maybe try to export LST into NIL8
  - [ ] line wrapping algorithm for JSON, NIL8, and eventually OSH and YSH
- Yaks / NIL8
  - [ ] write fibonacci program and compile it
  - [ ] Pea exports fibonacci program to Yaks

(much later: rewrite Yaks in Yaks, with NIL8 as IR for ASDL, re2c, and Ninja.  Some of this can go on the blog.)

**Comment by andychu** [comment]
Moved to #1874
