### ISSUE TITLE
Oils 0.22.0 TODO

### ISSUE THREAD

**Issue by andychu** [oilshell/oil#1874]
Copied from

- #1828 

---

-  Docs
   - [x] publish ref check metrics
- Performance
  - [x] here docs -- try temp files first, to be like other shells
- OSH
  - [x] ${a[@]+foo} issue from Samuel, for Nix
- YSH
  - [x] @() semantics -- #1126 
  - [x] #1850 
  - [x] #1849 
  - [x] #1841 
  - [ ] more breaking changes like `shopt --unset copy_env`
  - [x] argv and proc simplifications mentioned on blog - ARGV mutable, A local
  - [ ] #1830 
  - [ ] #1833  
- J8
  - [x] json/json8 builtin should take named args, not flags - breaking?

----

LATER, deferred

- Other YSH
  - [ ] Eggex names exported by `~`
  - [ ] `Str => replace()` could take a function (low priority)
  - [ ] is there anything with REG_NOTBOL?
- J8
  - [ ] line-based error messages for J8 - also affects NIL8
  - [x] check max code point in survey, json string, j8 string, code string
- Yaks / NIL8
  - [ ] write fibonacci program and compile it
  - [ ] Pea exports fibonacci program to Yaks

(much later: rewrite Yaks in Yaks, with NIL8 as IR for ASDL, re2c, and Ninja.  Some of this can go on the blog.)

**Comment by andychu** [comment]
Closing in favor of

- #1980
