### ISSUE TITLE
Eggex TODO

### ISSUE THREAD

**Issue by andychu** [oilshell/oil#490]
- [ ] multiline syntax
- [ ] API: if, for/while, sub, split
  - findall could be `list(mystr ~~ pat)` perhaps?
- [ ] adjust capturing syntax
- [ ] implement flags and translation preferences
- [ ] inline syntax `egrep $/d+/ foo.txt`

**Comment by andychu** [comment]
Issues exposed by this example:

https://news.ycombinator.com/item?id=26408510

- capturing and replacing API
- multiline eggex are way more readable.  However omitting newlines doesn't work with `/`, only `///`
